### PR TITLE
fix email validator

### PR DESCRIPTION
**Pull request by shiyiya**

### CODE REVIEW

**Comment by shiyiya** [comment]
https://github.com/Khanhtran47/Sora/issues/293#issuecomment-1374415291

**Comment by shiyiya** [comment]
now ,display
image
how get code? 😭

**Review by Khanhtran47 — CHANGES_REQUESTED** [review]
@shiyiya I think you need to update this code for sign-in.tsx file too

**Comment by Khanhtran47** [comment]
> now ,display image how get code? 😭

@shiyiya I just removed it, could you try signing up again

**Comment by shiyiya** [comment]
> @shiyiya I think you need to update this code for sign-in.tsx file too

sign-in.tsx is ok

**Review by Khanhtran47 — APPROVED** [review]

**Comment by shiyiya** [comment]
> > now ,display image how get code? 😭
> 
> @shiyiya I just removed it, could you try signing up again

still the same

image

**Comment by Khanhtran47** [comment]
@shiyiya sr, my mistake 🥲, this link works 
https://sora-c345qjs8h-khanhtran47.vercel.app/sign-up

**Comment by shiyiya** [comment]
The registration seems to be successful but no mail is received

**Comment by Khanhtran47** [comment]
> The registration seems to be successful but no mail is received

@shiyiya maybe you can check spam or other tabs

**Comment by shiyiya** [comment]
done. thanks

**Pull request merged**
